### ISSUE TITLE
Action fires too often?

### ISSUE THREAD

**Issue by rauchg** [hharnisc/hypercwd#13]
I was playing with the Redux Devtools when I noticed that `SESSION_SET_CWD` fires waaaay too often? Maybe worth doing a comparison before dispatching?

![image](https://cloud.githubusercontent.com/assets/13041/21753155/63a08ebe-d59b-11e6-8b7a-c0da0c186a86.png)

**Comment by hharnisc** [comment]
Wow, didn't realize it was firing that often! I wonder how much that's impacting performance? Should be a quick fix, let's see if I can get that out there in the next 30 minutes 😄

**Comment by hharnisc** [comment]
Hey @rauchg I've got the change in place, tested it locally and pushed out to NPM - https://www.npmjs.com/package/hypercwd 

Could you let me know if you're stilling seeing that issue when you get a chance?

**Comment by rauchg** [comment]
:O :O :O

**Comment by rauchg** [comment]
Impressive. Works like a charm!

**Comment by hharnisc** [comment]
Woo hoo! Thanks for digging into this, latest Hyper performance enhancements have been 🔥🔥🔥
