### ISSUE TITLE
Error: Command failed

### ISSUE THREAD

**Issue by cakenggt** [hharnisc/hypercwd#14]
When I start up Hyper, I get multiple instances of this error, which also happens whenever I `ctrl`+`t` to get a new tab. I am on Windows 7, and when I try to execute the `lsof` command in my shell, it says it is unrecognized, so maybe this is a problem with Windows not having a lot of unix commands.

```
C:\Users\username\.hyper_plugins\node_modules\hypercwd\index.js:10 Error: Command failed: lsof -p 1952 | grep cwd | tr -s ' ' | cut -d ' ' -f9-
'lsof' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by henrikdahl** [comment]
@cakenggt cwd fetching command that this plugin relies on is not supported by Windows.

**Comment by rbnlffl** [comment]
Is there anything planned for Windows?

**Comment by hharnisc** [comment]
Hey @cakenggt I've updated the pluggin to support windows. If you update `hypercwd` to version 1.0.0 or newer you should get the new features for windows.
