### ISSUE TITLE
Not working if starting shell on specified dir

### ISSUE THREAD

**Issue by bntzio** [hharnisc/hypercwd#15]
Whenever I start a new window I want to start on the **~/code** directory.

So I have this on my **~/.zshrc** file:

`cd ~/code`

This seems to override hypercwd, any suggestions on making hypercwd work with this config?

**Comment by hharnisc** [comment]
I think the ~/.zshrc is always going to win in this case, since it runs after `hyper` opens a new terminal session. However I'm working on making `hypercwd` that would allow you to configure a starting directory.

**Comment by hharnisc** [comment]
Going to close this as a duplicate of #2
