### ISSUE TITLE
No effect using Windows' CMD

### ISSUE THREAD

**Issue by colbin8r** [hharnisc/hypercwd#18]
I *really* like the idea of this HyperTerm plugin, but on my Windows machine, it doesn't seem to have any effect. Opening another tab doesn't `cd` to any other directories automatically; it always opens to my user folder (`%userprofile%`).

I've got mingw64 binaries in my PATH so I have access to some POSIX commands like `cd` and `pwd`. I'm not using the Bash built into windows like in issue #16 (although I may explore this as a decent alternative to mingw64 to get a native bash shell instead of cmd.exe).

If you have any questions as to my setup, ask away!

**Comment by colbin8r** [comment]
Is this a dup? I thought I read somewhere that Windows support wasn't planned. Is that the case?

**Comment by hharnisc** [comment]
Hey @colbin8r I've updated `hypercwd` so it work on windows now. If you install version 1.0.0 you should get the pluggin with windows support. Going to close this one for now, please re-open this one if the pluggin doesn't work for you!
