### ISSUE TITLE
Cursor/typing lag

### ISSUE THREAD

**Issue by genu** [hharnisc/hypercwd#19]
I don't know if this is particularly related to this plugin, but every time I have this installed and enabled it adds a noticeable cursor lag when I type. It would seem that its totally unrelated to this plugin, but I'm noticing it only when I have it enabled.

I can provide a gif illustrating the behavior if its not clear.

**Comment by genu** [comment]
Its possible that its caused by the  `SESSION_PTY_DATA` action since its firing every time the input changes.

**Comment by hharnisc** [comment]
Hey @genu 👋 

The current implementation uses that event to detect changes on the session. So every time the session changes (new input or output) it takes a look at the current working directory. There might be some optimizations but that's the best I could come up with to get something working. Open to ideas on how to improve this 😄
