### ISSUE TITLE
Close window issue with `initialWorkingDirectory`

### ISSUE THREAD

**Issue by bhardy** [hharnisc/hypercwd#28]
Hey,

Great plugin. I've been using it for quite a while with no issues and I'm sure it's saved me hours of time.

The other day I was looking through the options and I found `initialWorkingDirectory`—which is perfect for me, as all of my development work is in in the same base directory. I set it to `initialWorkingDirectory: "~/Development"`, and everything seemed to be working fine until I caught a bug.

Today I was simply trying to close all my Hyper terminals with cmd+w, and that's when I realized I couldn't close the window anymore. All the tabs go away, but I'm left with a little useless 
ghost window.

![hypercwd](https://user-images.githubusercontent.com/1272130/30234274-6ab280ca-94b0-11e7-8169-594b08573c05.png)

After a little troubleshooting (disabling every other plugin) I realized it was caused entirely by the `initialWorkingDirectory` option. I've attached a screenshot.

I'm on macOS and using oh-my-zsh.

**Comment by hharnisc** [comment]
Thanks so much for the report @bhardy - can definitely reproduce this! Digging into it now 😄

**Comment by hharnisc** [comment]
Hey @bhardy I figured out what was going on - it was creating a `null` session and `Hyper` never ends up destroying it. I submitted a PR to `Hyper` to fix this, so it might be a bit before it gets deployed to production. More details on that here: https://github.com/zeit/hyper/pull/2191

**Comment by bhardy** [comment]
@hharnisc, right on. Thanks again for the great plugin.

**Comment by mhxbe** [comment]
It seems that your pull-request already shipped with version 1.4.4 of Hyper.
https://github.com/zeit/hyper/commits/1.4.4

Thanks a lot!
