### ISSUE TITLE
Can't open new tab

### ISSUE THREAD

**Issue by spences10** [hharnisc/hypercwd#31]
Hi,

Windows 10 Pro user here, when I Shift+Ctrl+t for a new tab I get the error message in ther picture here:

![2017-09-23 2](https://user-images.githubusercontent.com/234708/31092821-8d0741ec-a7a7-11e7-867a-689a3721aa5f.png)

I'm using Hyper 1.4.8

Thanks

**Comment by hharnisc** [comment]
Hey @spences10 do you have any other plugins installed? Also could you double check the installed version, from the stack it looks like that might be coming from Hyper `v2.0.2`

**Comment by spences10** [comment]
Okke, I removed all the plug-ins and added them back in until I got the error. 

It was when I added this one back in it gave that error

I'm in the latest of this package and hyper

Thanks :+👍

**Comment by spences10** [comment]
Can I leave this with you now @hharnisc?
