### ISSUE TITLE
Hyper Canary - Slow stream from running programs

### ISSUE THREAD

**Issue by richrace** [hharnisc/hypercwd#37]
Setup: 
![screen shot 2018-01-12 at 10 52 59](https://user-images.githubusercontent.com/1273965/34871789-c9588d66-f786-11e7-9ec9-005ac0f08b2c.png)

Issue:
Visible slow down with streaming output from command or log files.

Test:
```bash
for ((i=1; i<=10000; i++)); do
   echo $i
done
```

**Comment by hharnisc** [comment]
Hey @richrace :wave: 

Thank you for the report here, this one has been an issue for quite some time - this snippet is great for reproduce the issue (was using the yes command which would always cause it to hang :smile: ). Unfortunately with the current implementation of Hyper, we have to check the process (almost) every time the output changes on the console. So the trade off is efficiency vs usefulness. -- I need to double check what's different in the 2.X canary release, if that changed we might be able to fix this!

**Comment by rauchg** [comment]
Just ran into this as well. `yes` in Hyper canary is nearly native-like, but if I turn on `hypercwd`, it barely renders.

I have an idea for a new strategy: only obtain the cwd upon creating a new tab or window. Don't do anything when the terminal is rendering.

**Comment by Esteban-Rocha** [comment]
Same here got to deactivate until this is fixed

**Comment by hharnisc** [comment]
Grabbed some performance data from chrome dev tools. Comparing the performance of the following script (basically the same as what you shared @richrace) on Hyper 2.0.0-canary.14:

```
for i in `seq 1 10000`;
do
  echo $i
done
```

Note: these comparisons are done while collecting performance metrics so the values don't reflect the actual performance -- the difference in performance under the same conditions is what is important here.

Without `hypercwd`: 

Render Time: ~359.8ms
Min FPS: ~5 

![without-hyper-cwd](https://user-images.githubusercontent.com/1388079/37606182-dbb36ce6-2b62-11e8-8f3b-63b10d00a28d.png)

With `hypercwd`:

Render Time: **~60 Seconds** (yes seconds!)
Min FPS: **0** 

![with-hypercwd](https://user-images.githubusercontent.com/1388079/37606471-8820be48-2b63-11e8-8dba-892c492594ff.png)

It's clear in this view how expensive the `spawn` is -- and much more of an issue when streaming logs etc.

![spawn](https://user-images.githubusercontent.com/1388079/37606713-1eb0c33a-2b64-11e8-97e4-81af0276e25b.png)

It's much more clear what's happening under the hood -- and I've got a couple ideas on how to fix this. Thank you for the input everyone :raised_hands:

**Comment by hharnisc** [comment]
I implemented an `edge trigger` function -- think `debounce`, but runs the passed in function at beginning *and* the end. And got pretty much the same performance as hyper without the plug ins. I'll deploy this soon! cc/ @rauchg 

Render Time: ~428.1ms
Min FPS: ~4

![image](https://user-images.githubusercontent.com/1388079/37619945-dde87d1e-2b88-11e8-9d90-0fbaf145bf58.png)

This fix should dramatically improve performance on OS X + Windows

**Comment by hharnisc** [comment]
Just published 1.2.1 release if you'd like to give this a try @rauchg @richrace @Esteban-Rocha

**Comment by richrace** [comment]
Brilliant. That works a treat 👍 

I've patch my local copy of https://github.com/henrikdahl/hyper-statusline with your changes and it fixes https://github.com/henrikdahl/hyper-statusline/issues/69 too!

**Comment by bmrobin** [comment]
>I've patch my local copy of https://github.com/henrikdahl/hyper-statusline with your changes and it fixes henrikdahl/hyper-statusline#69 too!

@richrace would you mind submitting a PR with that change to the hyper-statusline repository? i don't see any activity there related to fixing this issue and if you already have @hharnisc 's solution implemented then we could get that merged into the other project as well.

**Comment by Exomnius** [comment]
@richrace is it possible that you share your fix for https://github.com/henrikdahl/hyper-statusline too?

**Comment by j-f1** [comment]
@richrace If you open a PR on [my fork](https://github.com/j-f1/forked-hyper-statusline), I’ll get it released to npm.
