### ISSUE TITLE
Throw Execption when create a new PANEL in a SSH session

### ISSUE THREAD

**Issue by nielsonsantana** [hharnisc/hypercwd#39]
When I try open another panel in a SSH session, throw this exception. 
Maybe, the default behavior would open the last directory of source panel OR open the default folder.

![image](https://user-images.githubusercontent.com/627596/38425695-f4d0cfc6-398a-11e8-9a38-4c7a3604cf0f.png)

**Comment by hharnisc** [comment]
Hey @nielsonsantana is this still happening with Hyper v2.0? It looks like this is on an older version of Hyper (1.4.8)
