### ISSUE TITLE
hypercwd Breaks on Hyper v2

### ISSUE THREAD

**Issue by danyfu** [hharnisc/hypercwd#45]
On Hyper v2, this plugin crash.

![image](https://user-images.githubusercontent.com/9112457/39321965-4aea2e22-493d-11e8-8b5f-6d46a0db130f.png)

- Don't show the actual directory.
- If I add a space, puts a big space like a tab.
- Can't remove the character I put in the console.

This is what developers tools throws.
![image](https://user-images.githubusercontent.com/9112457/39321821-dc3c5bc6-493c-11e8-93ff-04a08dc6bdc0.png)

**Comment by asyncore** [comment]
There's a simple fix for that: PR #44. Just need someone to merge the PR and release v1.2.3.

**Comment by asyncore** [comment]
and it affects all Windows users.

**Comment by laurensiusadi** [comment]
@asyncore Thanks for the simple fix! https://github.com/hharnisc/hypercwd/pull/44/commits/9926b0a1a12c3f35b263e0aae8d2d3f42a14f8be

**Comment by hharnisc** [comment]
@asyncore's fix has been published as `1.2.3` thanks so much!
