### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rhys-vdw** [hharnisc/hypercwd#5]
This just doesn't work for me. I've added it to `.hyperterm.js`, it installed correctly, but new tabs open at `~`.

**Comment by rhys-vdw** [comment]
How should I debug this?

**Comment by hharnisc** [comment]
Hello @rhys-vdw 👋

Could you share the `hyperterm` and `hypercwd` versions, also any packages you've got installed?

**Comment by rhys-vdw** [comment]
Oh, sorry.

hypercwd - 0.1.5
hyperterm - 0.7.1.36

**Comment by rhys-vdw** [comment]
@hharnisc I seem to have fixed the problem. Seems it was some configuration in oh-my-zsh that was (presumably after your plugin ran) changing the default directory. Everything is working fine. Sorry for the false report.

**Comment by tleunen** [comment]
Hmm.. I'm using zpresto and I'm having the same issue. New tabs always opened to `~/`, even with this plugin.

Using hyperterm Version 0.7.1 (0.7.1.36)

**Comment by rhys-vdw** [comment]
Yeah. I keep hitting this as well actually. Also another guy using the same setup I know told me that he gets this problem intermittently.

**Comment by hharnisc** [comment]
Same issue as #4
