### ISSUE TITLE
Broken on Hyper 3.0.0-canary.1

### ISSUE THREAD

**Issue by Dids** [hharnisc/hypercwd#59]
Breaks things like new tabs entirely.

Note that Hyper 3.x now use both WebGL and Electron v4, which are likely related:
https://github.com/zeit/hyper/pull/3329
https://github.com/zeit/hyper/pull/3368

```
Uncaught (in promise) TypeError: newCwd.trim is not a function
    at setCwd (/Users/dids/.hyper_plugins/node_modules/hypercwd/setCwd.js:9)
```

**Comment by hharnisc** [comment]
Fixed by #60
